In [19]:
import seaborn as sns

In [20]:
df=sns.load_dataset("tips")

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [22]:
df.head(5)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [23]:
df["day"].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [24]:
df["smoker"].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [25]:
df["time"].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [26]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
columns=df.columns
categorical_columns=[column for column in columns if df[column].dtype=="category"]
categorical_columns

['sex', 'smoker', 'day', 'time']

In [27]:
X=df.drop(columns=["total_bill"])
y=df['total_bill']

In [28]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [29]:
day_encoder=LabelEncoder()
smoker_encoder=LabelEncoder()
time_encoder=LabelEncoder()
sex_encoder=LabelEncoder()
X_train["day"]=day_encoder.fit_transform(X_train["day"])
X_test["day"]=day_encoder.transform(X_test["day"])
X_train["smoker"]=smoker_encoder.fit_transform(X_train["smoker"])
X_test["smoker"]=smoker_encoder.transform(X_test["smoker"])
X_train["time"]=time_encoder.fit_transform(X_train["time"])
X_test["time"]=time_encoder.transform(X_test["time"])
X_train["sex"]=sex_encoder.fit_transform(X_train["sex"])
X_test["sex"]=sex_encoder.transform(X_test["sex"])

In [30]:
X_test.head(1)

     tip  sex  smoker  day  time  size
24  3.18    1       0    1     0     2

In [31]:
from sklearn.svm import SVR
model=SVR()

In [32]:
model.fit(X_train.drop(columns=categorical_columns),y_train)

SVR()

In [33]:
from sklearn.metrics import mean_squared_error,r2_score
print(mean_squared_error(y_test,model.predict(X_test.drop(columns=categorical_columns))))
print(r2_score(y_test,model.predict(X_test.drop(columns=categorical_columns))))

39.17807152655423
0.5379320164494539

In [34]:
X_train.columns

Index(['tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='str')

In [37]:
day_encoder.inverse_transform(X_train['day'])

array(['Sat', 'Sat', 'Fri', 'Sun', 'Thur', 'Sun', 'Thur', 'Sun', 'Sat',
       'Sun', 'Sat', 'Sun', 'Sun', 'Sun', 'Fri', 'Sat', 'Sat', 'Sat',
       'Sat', 'Sat', 'Sun', 'Sun', 'Sat', 'Thur', 'Sat', 'Sat', 'Sat',
       'Sun', 'Sun', 'Sat', 'Thur', 'Thur', 'Sun', 'Sat', 'Thur', 'Sat',
       'Sun', 'Sat', 'Sun', 'Sat', 'Sat', 'Sun', 'Sat', 'Thur', 'Fri',
       'Sun', 'Sun', 'Fri', 'Thur', 'Thur', 'Sat', 'Sun', 'Sat', 'Fri',
       'Thur', 'Thur', 'Sat', 'Sat', 'Sat', 'Sun', 'Thur', 'Sun', 'Sun',
       'Thur', 'Sun', 'Fri', 'Thur', 'Thur', 'Sun', 'Fri', 'Thur', 'Sat',
       'Sun', 'Fri', 'Sat', 'Thur', 'Sat', 'Sat', 'Thur', 'Sun', 'Thur',
       'Sun', 'Sat', 'Sat', 'Sun', 'Sun', 'Thur', 'Sat', 'Thur', 'Sun',
       'Thur', 'Sat', 'Thur', 'Thur', 'Fri', 'Sun', 'Sat', 'Thur', 'Sat',
       'Sun', 'Sat', 'Sat', 'Thur', 'Sat', 'Sun', 'Sun', 'Thur', 'Sat',
       'Thur', 'Sun', 'Fri', 'Sun', 'Sun', 'Thur', 'Sun', 'Sun', 'Sat',
       'Sun', 'Thur', 'Fri', 'Sat', 'Fri', 'Sun', 'Sun', 'Thur', 'Sat',
       'Thur', 'Sun', 'Sat', 'Sat', 'Fri', 'Thur', 'Sat', 'Fri', 'Thur',
       'Sun', 'Sun', 'Sat', 'Sat', 'Thur', 'Sun', 'Sun', 'Sat', 'Sat',
       'Thur', 'Thur', 'Fri', 'Sat', 'Sun', 'Sat', 'Sun', 'Sat', 'Sun',
       'Sat', 'Sun', 'Sat', 'Sat', 'Sat', 'Sat', 'Sun', 'Thur', 'Sat',
       'Sat', 'Thur', 'Sun', 'Sat', 'Sun', 'Thur', 'Thur', 'Sat', 'Sun',
       'Sat', 'Sun', 'Sun', 'Thur', 'Thur', 'Sun', 'Sat', 'Fri', 'Sun',
       'Thur', 'Thur', 'Sat', 'Sat', 'Sat', 'Thur', 'Thur', 'Sat', 'Sun',
       'Sat', 'Sat', 'Sun', 'Fri', 'Sun', 'Sat'], dtype=object)

In [38]:
day_encoder.inverse_transform(X_test['day'])

array(['Sat', 'Sun', 'Sun', 'Sat', 'Thur', 'Sun', 'Thur', 'Thur', 'Sun',
       'Fri', 'Sun', 'Sat', 'Thur', 'Sun', 'Thur', 'Thur', 'Thur', 'Sun',
       'Sat', 'Thur', 'Sat', 'Sat', 'Sat', 'Sat', 'Sun', 'Thur', 'Sun',
       'Sat', 'Sun', 'Sun', 'Sun', 'Sat', 'Sat', 'Sat', 'Sun', 'Thur',
       'Fri', 'Thur', 'Thur', 'Sat', 'Sat', 'Thur', 'Sun', 'Sun', 'Thur',
       'Sat', 'Sat', 'Sat', 'Thur'], dtype=object)