In [36]:
import numpy as np
import pandas as pd

In [37]:
data={
    "x1":[0,0,1,1],
    "x2":[0,1,0,1],
    "y":[0,0,0,1]
}

In [38]:
AND=pd.DataFrame(data)

In [39]:
AND

   x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [40]:
X=AND.drop(columns=['y'])
y=AND['y']
y.to_frame()

   y
0  0
1  0
2  0
3  1

In [41]:
print(X)
print(y)

   x1  x2
0   0   0
1   0   1
2   1   0
3   1   1
0    0
1    0
2    0
3    1
Name: y, dtype: int64

In [42]:
bias=np.c_[X,-np.ones((len(X),1))]

In [43]:
bias

array([[ 0.,  0., -1.],
       [ 0.,  1., -1.],
       [ 1.,  0., -1.],
       [ 1.,  1., -1.]])